# ============================================================================
# File: 02_analyze_extreme_event_case_crossover_simulation.R
# Purpose:
#   Analyze simulation data generated by
#   01_generate_extreme_event_case_crossover_simulation.R and compare four
#   estimators of the additional extreme-event-history log mortality rate ratio.
#
# Estimators:
#   1. Conventional conditional logistic regression.
#   2. Outcome-model estimating-equation estimator (f = 0).
#   3. Exposure-regression estimating-equation estimator (g = 0).
#   4. Proposed generalized AIPW estimator.
#
# Primary performance metrics:
#   - Scenario-specific absolute empirical coefficient bias.
#   - Overall mean absolute coefficient bias across the three scenarios in
#     which at least one nuisance model is correctly specified.
#   - Worst-case absolute coefficient bias across those three scenarios.
#   - Overall mean absolute bias of the mean annual attributable fraction.
#   - Mean empirical 95% confidence interval coverage.
#   - Numerical convergence rate.
#
# Fixed project path:
#   /xxx/ccc
#
# Optional environment variables:
#   EXTREME_ANALYSIS_WORKERS         = parallel workers; default 1
#   EXTREME_ANALYSIS_OVERWRITE       = TRUE/FALSE; default FALSE
#   EXTREME_ANALYSIS_MAX_REPLICATES  = maximum replicates per scenario;
#                                      0 means use all available replicates
#   EXTREME_XGB_THREADS              = XGBoost threads per model; default 1
# ============================================================================

options(stringsAsFactors = FALSE)

required_packages <- c("data.table", "survival", "xgboost", "openxlsx")
missing_packages <- required_packages[
  !vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)
]
if (length(missing_packages) > 0L) {
  stop(
    "Missing required package(s): ",
    paste(missing_packages, collapse = ", "),
    ". Install them before running this script.",
    call. = FALSE
  )
}

suppressPackageStartupMessages({
  library(data.table)
  library(survival)
  library(xgboost)
  library(openxlsx)
})

# ----------------------------------------------------------------------------
# 1. Paths and analysis settings
# ----------------------------------------------------------------------------

PROJECT_ROOT <- "/xxx/ccc"
EXTREME_SIM_ROOT <- file.path(PROJECT_ROOT, "extreme_event_simulation")
INPUT_DIR <- file.path(EXTREME_SIM_ROOT, "simulated_data")
RESULT_DIR <- file.path(EXTREME_SIM_ROOT, "results")
REPLICATE_RESULT_DIR <- file.path(RESULT_DIR, "replicate_results")

ANALYSIS_SEED <- 20260714L
N_WORKERS <- suppressWarnings(as.integer(
  Sys.getenv("EXTREME_ANALYSIS_WORKERS", unset = "1")
))
OVERWRITE <- toupper(
  Sys.getenv("EXTREME_ANALYSIS_OVERWRITE", unset = "FALSE")
) %in% c("TRUE", "T", "1", "YES", "Y")
MAX_REPLICATES_PER_SCENARIO <- suppressWarnings(as.integer(
  Sys.getenv("EXTREME_ANALYSIS_MAX_REPLICATES", unset = "0")
))
XGB_THREADS <- suppressWarnings(as.integer(
  Sys.getenv("EXTREME_XGB_THREADS", unset = "1")
))

if (!is.finite(N_WORKERS) || N_WORKERS < 1L) N_WORKERS <- 1L
if (!is.finite(XGB_THREADS) || XGB_THREADS < 1L) XGB_THREADS <- 1L
if (!is.finite(MAX_REPLICATES_PER_SCENARIO) ||
    MAX_REPLICATES_PER_SCENARIO < 0L) {
  MAX_REPLICATES_PER_SCENARIO <- 0L
}

analysis_cfg <- list(
  analysis_seed = ANALYSIS_SEED,
  n_workers = N_WORKERS,
  overwrite = OVERWRITE,
  max_replicates_per_scenario = MAX_REPLICATES_PER_SCENARIO,
  xgb_threads = XGB_THREADS,
  xgb_nrounds = 180L,
  xgb_max_depth = 3L,
  xgb_min_child_weight = 5,
  xgb_eta = 0.05,
  xgb_subsample = 0.80,
  xgb_colsample_bytree = 0.85,
  score_tolerance = 1e-8,
  parameter_tolerance = 1e-8,
  maximum_newton_iterations = 100L,
  maximum_absolute_eta = 700,
  primary_scenarios = c(
    "S1_both_correct",
    "S2_outcome_correct_exposure_misspecified",
    "S3_outcome_misspecified_exposure_correct"
  ),
  all_scenarios = c(
    "S1_both_correct",
    "S2_outcome_correct_exposure_misspecified",
    "S3_outcome_misspecified_exposure_correct",
    "S4_both_misspecified"
  )
)

for (directory_path in c(RESULT_DIR, REPLICATE_RESULT_DIR)) {
  if (!dir.exists(directory_path)) {
    dir.create(directory_path, recursive = TRUE, showWarnings = FALSE)
  }
}

manifest_path <- file.path(INPUT_DIR, "simulation_manifest.csv")
scenario_design_path <- file.path(INPUT_DIR, "scenario_design.csv")
configuration_path <- file.path(INPUT_DIR, "simulation_configuration.rds")

if (!file.exists(manifest_path) ||
    !file.exists(scenario_design_path) ||
    !file.exists(configuration_path)) {
  stop(
    "Simulation inputs are missing. Run the data-generation script first.",
    call. = FALSE
  )
}

manifest <- fread(manifest_path)
scenario_design <- fread(scenario_design_path)
simulation_configuration <- readRDS(configuration_path)
set.seed(ANALYSIS_SEED)

if (MAX_REPLICATES_PER_SCENARIO > 0L) {
  manifest <- manifest[
    order(replicate),
    head(.SD, MAX_REPLICATES_PER_SCENARIO),
    by = scenario_id
  ]
}
setorder(manifest, scenario_id, replicate)

# ----------------------------------------------------------------------------
# 2. General helper functions
# ----------------------------------------------------------------------------

expit <- function(x) {
  output <- numeric(length(x))
  positive <- x >= 0
  output[positive] <- 1 / (1 + exp(-x[positive]))
  exp_x <- exp(x[!positive])
  output[!positive] <- exp_x / (1 + exp_x)
  output
}

mean_or_na <- function(x) {
  valid <- is.finite(x)
  if (!any(valid)) return(NA_real_)
  mean(x[valid])
}

max_or_na <- function(x) {
  valid <- is.finite(x)
  if (!any(valid)) return(NA_real_)
  max(x[valid])
}

min_or_na <- function(x) {
  valid <- is.finite(x)
  if (!any(valid)) return(NA_real_)
  min(x[valid])
}

extract_named_value <- function(vector_object, name, default = NA_real_) {
  if (is.null(vector_object) || !name %in% names(vector_object)) return(default)
  value <- unname(vector_object[[name]])
  if (!is.finite(value)) default else value
}

# ----------------------------------------------------------------------------
# 3. Conditional logistic outcome nuisance model
# ----------------------------------------------------------------------------

add_outcome_basis <- function(day_data) {
  output <- copy(day_data)
  output[, sin_x1 := sin(x1)]
  output[, x1_sq := x1^2]
  output[, x1_x2 := x1 * x2]
  output[]
}

outcome_covariate_names <- function(specification) {
  if (identical(specification, "correct")) {
    return(c("sin_x1", "x1_sq", "x2", "x1_x2", "x3", "holiday"))
  }
  if (identical(specification, "misspecified")) {
    return(c("x1", "x2", "x3", "holiday"))
  }
  stop("Unknown outcome nuisance specification: ", specification, call. = FALSE)
}

make_clogit_formula <- function(specification) {
  nuisance_terms <- outcome_covariate_names(specification)
  as.formula(
    paste(
      "case ~ event + heat + cold +",
      paste(nuisance_terms, collapse = " + "),
      "+ strata(set_id)"
    )
  )
}

fit_clogit_safely <- function(day_data, specification) {
  model_formula <- make_clogit_formula(specification)
  tryCatch(
    survival::clogit(
      formula = model_formula,
      data = day_data,
      method = "efron",
      control = survival::coxph.control(iter.max = 50L, eps = 1e-9)
    ),
    error = function(e) {
      structure(
        list(error_message = conditionMessage(e)),
        class = "failed_clogit"
      )
    }
  )
}

extract_model_coefficients <- function(model, coefficient_names) {
  output <- setNames(rep(0, length(coefficient_names)), coefficient_names)
  if (inherits(model, "failed_clogit")) return(output)
  
  estimated <- coef(model)
  common_names <- intersect(names(estimated), coefficient_names)
  if (length(common_names) > 0L) {
    output[common_names] <- unname(estimated[common_names])
  }
  output[!is.finite(output)] <- 0
  output
}

fit_crossfitted_outcome_nuisance <- function(day_data, specification) {
  working <- add_outcome_basis(day_data)
  working[, g_hat_day := NA_real_]
  
  fold_values <- sort(unique(working$fold))
  nuisance_names <- outcome_covariate_names(specification)
  fold_records <- vector("list", length(fold_values))
  
  for (fold_index in seq_along(fold_values)) {
    held_out_fold <- fold_values[fold_index]
    training_data <- working[fold != held_out_fold]
    test_indices <- which(working$fold == held_out_fold)
    test_data <- working[test_indices]
    
    model <- fit_clogit_safely(training_data, specification)
    if (inherits(model, "failed_clogit")) {
      return(list(
        success = FALSE,
        error_message = paste0(
          "Outcome nuisance model failed in fold ",
          held_out_fold,
          ": ",
          model$error_message
        ),
        day_data = working,
        fold_records = data.table()
      ))
    }
    
    all_required_names <- c("event", "heat", "cold", nuisance_names)
    coefficients <- extract_model_coefficients(model, all_required_names)
    
    nuisance_matrix <- as.matrix(test_data[, ..nuisance_names])
    nuisance_part <- as.numeric(
      nuisance_matrix %*% coefficients[nuisance_names]
    )
    
    # For the event-history target, g includes the background heat/cold terms
    # and all remaining outcome nuisance terms, but excludes alpha * event.
    g_hat <- coefficients["heat"] * test_data$heat +
      coefficients["cold"] * test_data$cold +
      nuisance_part
    
    working[test_indices, g_hat_day := g_hat]
    
    fold_records[[fold_index]] <- data.table(
      fold = as.integer(held_out_fold),
      alpha_event = unname(coefficients["event"]),
      beta_heat = unname(coefficients["heat"]),
      beta_cold = unname(coefficients["cold"]),
      converged = TRUE
    )
  }
  
  if (any(!is.finite(working$g_hat_day))) {
    return(list(
      success = FALSE,
      error_message = "Cross-fitted outcome nuisance predictions were nonfinite.",
      day_data = working,
      fold_records = rbindlist(fold_records, fill = TRUE)
    ))
  }
  
  list(
    success = TRUE,
    error_message = "",
    day_data = working,
    fold_records = rbindlist(fold_records, fill = TRUE)
  )
}

fit_full_conventional_clogit <- function(day_data, specification) {
  working <- add_outcome_basis(day_data)
  model <- fit_clogit_safely(working, specification)
  
  if (inherits(model, "failed_clogit")) {
    return(list(
      estimator = "Conventional conditional logistic regression",
      alpha = NA_real_,
      se = NA_real_,
      converged = FALSE,
      error_message = model$error_message
    ))
  }
  
  coefficients <- coef(model)
  alpha <- extract_named_value(coefficients, "event")
  variance_matrix <- tryCatch(vcov(model), error = function(e) NULL)
  se <- NA_real_
  
  if (!is.null(variance_matrix) &&
      "event" %in% rownames(variance_matrix) &&
      is.finite(variance_matrix["event", "event"])) {
    se <- sqrt(max(variance_matrix["event", "event"], 0))
  }
  
  list(
    estimator = "Conventional conditional logistic regression",
    alpha = alpha,
    se = se,
    converged = is.finite(alpha),
    error_message = ""
  )
}

# ----------------------------------------------------------------------------
# 4. Ordered pseudo-pair construction
# ----------------------------------------------------------------------------

build_ordered_pseudo_pairs <- function(day_data_with_outcome_predictions) {
  member_columns <- c(
    "row_id", "event", "heat", "cold", "x1", "x2", "x3",
    "holiday", "set_context1", "set_context2", "g_hat_day"
  )
  
  set_columns <- c(
    "set_id", "scenario_id", "scenario_label", "replicate", "year",
    "fold", "n_controls", "true_alpha_event",
    "outcome_nuisance_spec", "exposure_nuisance_spec"
  )
  
  controls <- day_data_with_outcome_predictions[
    case == 0L,
    c(set_columns, member_columns),
    with = FALSE
  ]
  cases <- day_data_with_outcome_predictions[
    case == 1L,
    c("set_id", member_columns),
    with = FALSE
  ]
  
  setnames(controls, member_columns, paste0(member_columns, "_control"))
  setnames(cases, member_columns, paste0(member_columns, "_case"))
  
  comparisons <- merge(
    controls,
    cases,
    by = "set_id",
    all = FALSE,
    sort = FALSE
  )
  comparisons[, comparison_index := seq_len(.N), by = set_id]
  
  make_orientation <- function(first_suffix, second_suffix, d_value) {
    output <- comparisons[, ..set_columns]
    output[, comparison_index := comparisons$comparison_index]
    output[, D := as.integer(d_value)]
    
    for (variable_name in member_columns) {
      first_source <- paste0(variable_name, "_", first_suffix)
      second_source <- paste0(variable_name, "_", second_suffix)
      output[[paste0(variable_name, "_first")]] <- comparisons[[first_source]]
      output[[paste0(variable_name, "_second")]] <- comparisons[[second_source]]
    }
    output
  }
  
  control_first <- make_orientation("control", "case", 0L)
  case_first <- make_orientation("case", "control", 1L)
  pairs <- rbindlist(list(control_first, case_first), use.names = TRUE)
  
  pairs[, pair_id := sprintf(
    "%s_P%02d_O%d",
    set_id,
    comparison_index,
    D
  )]
  pairs[, z_event := event_first - event_second]
  pairs[, g_hat_pair := g_hat_day_first - g_hat_day_second]
  pairs[, pair_weight := 1 / (2 * n_controls)]
  pairs[, exposure_training_weight := 1 / n_controls]
  
  pairs[, heat_diff := heat_first - heat_second]
  pairs[, cold_diff := cold_first - cold_second]
  pairs[, x1_diff := x1_first - x1_second]
  pairs[, x2_diff := x2_first - x2_second]
  pairs[, x3_diff := x3_first - x3_second]
  pairs[, holiday_diff := holiday_first - holiday_second]
  
  pairs[, heat_mean := 0.5 * (heat_first + heat_second)]
  pairs[, cold_mean := 0.5 * (cold_first + cold_second)]
  pairs[, x1_mean := 0.5 * (x1_first + x1_second)]
  pairs[, x2_mean := 0.5 * (x2_first + x2_second)]
  pairs[, x3_mean := 0.5 * (x3_first + x3_second)]
  pairs[, holiday_mean := 0.5 * (holiday_first + holiday_second)]
  
  pairs[, heat_abs_diff := abs(heat_diff)]
  pairs[, cold_abs_diff := abs(cold_diff)]
  pairs[, x1_abs_diff := abs(x1_diff)]
  pairs[, x2_abs_diff := abs(x2_diff)]
  pairs[, x3_abs_diff := abs(x3_diff)]
  
  pairs[, year_centered := year - mean(2013:2019)]
  pairs[, year_sine := sin(2 * pi * (year - 2013) / 7)]
  pairs[, year_cosine := cos(2 * pi * (year - 2013) / 7)]
  
  setorder(pairs, set_id, comparison_index, D)
  pairs[]
}

exposure_feature_names <- function(specification) {
  if (identical(specification, "correct")) {
    return(c(
      "heat_first", "cold_first", "x1_first", "x2_first", "x3_first",
      "holiday_first",
      "heat_second", "cold_second", "x1_second", "x2_second",
      "x3_second", "holiday_second",
      "set_context1_first", "set_context2_first",
      "heat_diff", "cold_diff", "x1_diff", "x2_diff", "x3_diff",
      "holiday_diff",
      "heat_mean", "cold_mean", "x1_mean", "x2_mean", "x3_mean",
      "holiday_mean",
      "heat_abs_diff", "cold_abs_diff", "x1_abs_diff", "x2_abs_diff",
      "x3_abs_diff",
      "n_controls", "year_centered", "year_sine", "year_cosine"
    ))
  }
  
  if (identical(specification, "misspecified")) {
    return(c("x1_diff", "x2_diff", "holiday_diff"))
  }
  
  stop("Unknown exposure nuisance specification: ", specification, call. = FALSE)
}

# ----------------------------------------------------------------------------
# 5. Cross-fitted XGBoost exposure conditional-mean model
# ----------------------------------------------------------------------------

fit_crossfitted_exposure_nuisance <- function(
    pairs,
    specification,
    seed_base,
    analysis_cfg) {
  
  working <- copy(pairs)
  working[, f_hat := NA_real_]
  feature_names <- exposure_feature_names(specification)
  fold_values <- sort(unique(working$fold))
  fold_records <- vector("list", length(fold_values))
  
  for (fold_index in seq_along(fold_values)) {
    held_out_fold <- fold_values[fold_index]
    training_data <- working[fold != held_out_fold & D == 0L]
    test_indices <- which(working$fold == held_out_fold)
    test_data <- working[test_indices]
    
    if (nrow(training_data) == 0L || nrow(test_data) == 0L) {
      return(list(
        success = FALSE,
        error_message = paste0(
          "Empty exposure-model training or test sample in fold ",
          held_out_fold,
          "."
        ),
        pairs = working,
        fold_records = data.table()
      ))
    }
    
    training_matrix <- as.matrix(training_data[, ..feature_names])
    test_matrix <- as.matrix(test_data[, ..feature_names])
    
    dtrain <- xgboost::xgb.DMatrix(
      data = training_matrix,
      label = training_data$z_event,
      weight = training_data$exposure_training_weight
    )
    dtest <- xgboost::xgb.DMatrix(data = test_matrix)
    
    model_parameters <- list(
      objective = "reg:squarederror",
      eval_metric = "rmse",
      max_depth = analysis_cfg$xgb_max_depth,
      min_child_weight = analysis_cfg$xgb_min_child_weight,
      eta = analysis_cfg$xgb_eta,
      subsample = analysis_cfg$xgb_subsample,
      colsample_bytree = analysis_cfg$xgb_colsample_bytree,
      nthread = analysis_cfg$xgb_threads,
      seed = as.integer(seed_base + 100L * held_out_fold)
    )
    
    model <- tryCatch(
      xgboost::xgb.train(
        params = model_parameters,
        data = dtrain,
        nrounds = analysis_cfg$xgb_nrounds,
        verbose = 0
      ),
      error = function(e) {
        structure(
          list(error_message = conditionMessage(e)),
          class = "failed_xgboost"
        )
      }
    )
    
    if (inherits(model, "failed_xgboost")) {
      return(list(
        success = FALSE,
        error_message = paste0(
          "Exposure nuisance model failed in fold ",
          held_out_fold,
          ": ",
          model$error_message
        ),
        pairs = working,
        fold_records = data.table()
      ))
    }
    
    test_prediction <- as.numeric(predict(model, dtest))
    working[test_indices, f_hat := test_prediction]
    
    control_first_test <- test_data$D == 0L
    observed_control_first <- test_data$z_event[control_first_test]
    predicted_control_first <- test_prediction[control_first_test]
    
    fold_records[[fold_index]] <- data.table(
      fold = as.integer(held_out_fold),
      specification = specification,
      n_training_pairs = nrow(training_data),
      n_test_pairs = nrow(test_data),
      test_control_first_rmse = if (length(observed_control_first) > 0L) {
        sqrt(mean((observed_control_first - predicted_control_first)^2))
      } else {
        NA_real_
      },
      prediction_minimum = min(test_prediction),
      prediction_maximum = max(test_prediction)
    )
  }
  
  if (any(!is.finite(working$f_hat))) {
    return(list(
      success = FALSE,
      error_message = "Cross-fitted exposure nuisance predictions were nonfinite.",
      pairs = working,
      fold_records = rbindlist(fold_records, fill = TRUE)
    ))
  }
  
  list(
    success = TRUE,
    error_message = "",
    pairs = working,
    fold_records = rbindlist(fold_records, fill = TRUE)
  )
}

# ----------------------------------------------------------------------------
# 6. Scalar generalized estimating equation and clustered sandwich variance
# ----------------------------------------------------------------------------

compute_ee_moments <- function(
    alpha,
    pairs,
    g_values,
    f_values,
    analysis_cfg,
    return_rows = FALSE) {
  
  eta <- alpha * pairs$z_event + g_values
  negative_eta <- pmin(
    pmax(-eta, -analysis_cfg$maximum_absolute_eta),
    analysis_cfg$maximum_absolute_eta
  )
  
  # D/pi - 1 equals exp(-eta) when D=1 and -1 when D=0.
  multiplier <- ifelse(pairs$D == 1L, exp(negative_eta), -1)
  residualized_event <- pairs$z_event - f_values
  row_score <- pairs$pair_weight * residualized_event * multiplier
  
  n_sets <- uniqueN(pairs$set_id)
  mean_score <- sum(row_score) / n_sets
  
  row_derivative <- -pairs$pair_weight *
    residualized_event *
    pairs$D *
    exp(negative_eta) *
    pairs$z_event
  mean_jacobian <- sum(row_derivative) / n_sets
  
  output <- list(
    mean_score = mean_score,
    mean_jacobian = mean_jacobian,
    eta = eta
  )
  if (isTRUE(return_rows)) {
    output$row_score <- row_score
    output$row_derivative <- row_derivative
  }
  output
}

newton_solve_one_start <- function(
    starting_alpha,
    pairs,
    g_values,
    f_values,
    analysis_cfg) {
  
  alpha <- as.numeric(starting_alpha)[1L]
  if (!is.finite(alpha)) alpha <- 0
  
  current <- compute_ee_moments(
    alpha,
    pairs,
    g_values,
    f_values,
    analysis_cfg
  )
  converged <- FALSE
  iteration <- 0L
  
  for (iteration in seq_len(analysis_cfg$maximum_newton_iterations)) {
    if (!is.finite(current$mean_score) ||
        !is.finite(current$mean_jacobian) ||
        abs(current$mean_jacobian) < 1e-12) {
      break
    }
    
    if (abs(current$mean_score) <= analysis_cfg$score_tolerance) {
      converged <- TRUE
      break
    }
    
    newton_step <- current$mean_score / current$mean_jacobian
    if (!is.finite(newton_step)) break
    
    accepted <- FALSE
    best_alpha <- alpha
    best_moments <- current
    best_score <- abs(current$mean_score)
    
    for (damping in 2^-(0:15)) {
      candidate_alpha <- alpha - damping * newton_step
      candidate <- compute_ee_moments(
        candidate_alpha,
        pairs,
        g_values,
        f_values,
        analysis_cfg
      )
      
      if (is.finite(candidate$mean_score) &&
          abs(candidate$mean_score) < best_score) {
        best_alpha <- candidate_alpha
        best_moments <- candidate
        best_score <- abs(candidate$mean_score)
        accepted <- TRUE
        break
      }
    }
    
    if (!accepted) break
    
    parameter_change <- abs(best_alpha - alpha)
    alpha <- best_alpha
    current <- best_moments
    
    if (abs(current$mean_score) <= analysis_cfg$score_tolerance &&
        parameter_change <= analysis_cfg$parameter_tolerance) {
      converged <- TRUE
      break
    }
  }
  
  list(
    alpha = alpha,
    converged = converged ||
      abs(current$mean_score) <= analysis_cfg$score_tolerance,
    iterations = iteration,
    score = current$mean_score,
    jacobian = current$mean_jacobian
  )
}

fallback_scalar_root <- function(
    pairs,
    g_values,
    f_values,
    analysis_cfg,
    preferred_start = 0) {
  
  score_function <- function(alpha) {
    compute_ee_moments(
      alpha,
      pairs,
      g_values,
      f_values,
      analysis_cfg
    )$mean_score
  }
  
  grid <- seq(-3, 3, length.out = 241L)
  grid_scores <- vapply(grid, score_function, numeric(1))
  sign_change_indices <- which(
    is.finite(grid_scores[-length(grid_scores)]) &
      is.finite(grid_scores[-1L]) &
      grid_scores[-length(grid_scores)] * grid_scores[-1L] <= 0
  )
  
  roots <- numeric(0)
  if (length(sign_change_indices) > 0L) {
    roots <- vapply(sign_change_indices, function(index) {
      lower <- grid[index]
      upper <- grid[index + 1L]
      if (grid_scores[index] == 0) return(lower)
      if (grid_scores[index + 1L] == 0) return(upper)
      tryCatch(
        uniroot(score_function, interval = c(lower, upper), tol = 1e-10)$root,
        error = function(e) NA_real_
      )
    }, numeric(1))
    roots <- roots[is.finite(roots)]
  }
  
  if (length(roots) > 0L) {
    selected <- roots[which.min(abs(roots - preferred_start))]
    moments <- compute_ee_moments(
      selected,
      pairs,
      g_values,
      f_values,
      analysis_cfg
    )
    return(list(
      alpha = selected,
      converged = abs(moments$mean_score) <= 1e-7,
      iterations = NA_integer_,
      score = moments$mean_score,
      jacobian = moments$mean_jacobian
    ))
  }
  
  optimized <- tryCatch(
    optimize(
      f = function(alpha) abs(score_function(alpha)),
      interval = c(-3, 3),
      tol = 1e-10
    ),
    error = function(e) NULL
  )
  
  if (is.null(optimized)) {
    return(list(
      alpha = NA_real_,
      converged = FALSE,
      iterations = NA_integer_,
      score = NA_real_,
      jacobian = NA_real_
    ))
  }
  
  selected <- optimized$minimum
  moments <- compute_ee_moments(
    selected,
    pairs,
    g_values,
    f_values,
    analysis_cfg
  )
  
  list(
    alpha = selected,
    converged = abs(moments$mean_score) <= 1e-7,
    iterations = NA_integer_,
    score = moments$mean_score,
    jacobian = moments$mean_jacobian
  )
}

solve_generalized_ee <- function(
    pairs,
    g_values,
    f_values,
    starting_values,
    analysis_cfg) {
  
  starts <- unique(as.numeric(unlist(starting_values)))
  starts <- starts[is.finite(starts)]
  if (length(starts) == 0L) starts <- 0
  
  solutions <- lapply(starts, function(start_value) {
    newton_solve_one_start(
      starting_alpha = start_value,
      pairs = pairs,
      g_values = g_values,
      f_values = f_values,
      analysis_cfg = analysis_cfg
    )
  })
  
  converged_vector <- vapply(solutions, `[[`, logical(1), "converged")
  score_vector <- abs(vapply(solutions, `[[`, numeric(1), "score"))
  
  if (any(converged_vector, na.rm = TRUE)) {
    candidate_indices <- which(converged_vector)
    best_index <- candidate_indices[which.min(score_vector[candidate_indices])]
    best_solution <- solutions[[best_index]]
  } else {
    finite_indices <- which(is.finite(score_vector))
    if (length(finite_indices) > 0L) {
      best_index <- finite_indices[which.min(score_vector[finite_indices])]
      best_solution <- solutions[[best_index]]
    } else {
      best_solution <- list(alpha = NA_real_, converged = FALSE)
    }
    
    fallback <- fallback_scalar_root(
      pairs = pairs,
      g_values = g_values,
      f_values = f_values,
      analysis_cfg = analysis_cfg,
      preferred_start = starts[1L]
    )
    
    if (isTRUE(fallback$converged) ||
        (!is.finite(best_solution$alpha) && is.finite(fallback$alpha))) {
      best_solution <- fallback
    }
  }
  
  best_solution
}

compute_clustered_sandwich_se <- function(
    alpha,
    pairs,
    g_values,
    f_values,
    analysis_cfg) {
  
  moments <- compute_ee_moments(
    alpha,
    pairs,
    g_values,
    f_values,
    analysis_cfg,
    return_rows = TRUE
  )
  
  if (!is.finite(moments$mean_jacobian) ||
      abs(moments$mean_jacobian) < 1e-12) {
    return(NA_real_)
  }
  
  set_scores <- data.table(
    set_id = pairs$set_id,
    row_score = moments$row_score
  )[, .(set_score = sum(row_score)), by = set_id]
  
  n_sets <- nrow(set_scores)
  if (n_sets < 2L) return(NA_real_)
  
  centered_scores <- set_scores$set_score - mean(set_scores$set_score)
  score_variance <- sum(centered_scores^2) / (n_sets - 1L)
  variance_alpha <- score_variance /
    (n_sets * moments$mean_jacobian^2)
  
  if (!is.finite(variance_alpha) || variance_alpha < 0) return(NA_real_)
  sqrt(variance_alpha)
}

fit_one_ee_estimator <- function(
    estimator_name,
    pairs,
    g_values,
    f_values,
    starting_values,
    analysis_cfg) {
  
  solution <- solve_generalized_ee(
    pairs = pairs,
    g_values = g_values,
    f_values = f_values,
    starting_values = starting_values,
    analysis_cfg = analysis_cfg
  )
  
  if (!is.finite(solution$alpha)) {
    return(list(
      estimator = estimator_name,
      alpha = NA_real_,
      se = NA_real_,
      converged = FALSE,
      iterations = solution$iterations,
      score = solution$score,
      error_message = "No finite estimating-equation solution."
    ))
  }
  
  standard_error <- compute_clustered_sandwich_se(
    alpha = solution$alpha,
    pairs = pairs,
    g_values = g_values,
    f_values = f_values,
    analysis_cfg = analysis_cfg
  )
  
  list(
    estimator = estimator_name,
    alpha = solution$alpha,
    se = standard_error,
    converged = isTRUE(solution$converged),
    iterations = solution$iterations,
    score = solution$score,
    error_message = ""
  )
}

# ----------------------------------------------------------------------------
# 7. Mean annual additional event-history attributable fraction
# ----------------------------------------------------------------------------

compute_mean_annual_af <- function(burden_data, alpha) {
  if (!is.finite(alpha)) return(NA_real_)
  
  working <- copy(burden_data)
  working[, af := 1 - exp(-alpha * event)]
  annual <- working[, .(annual_af = mean(af)), by = year]
  mean(annual$annual_af)
}

# ----------------------------------------------------------------------------
# 8. One-replicate analysis
# ----------------------------------------------------------------------------

make_estimator_result_row <- function(
    fit_object,
    scenario_row,
    replicate_id,
    true_alpha,
    true_mean_annual_af,
    burden_data,
    generation_metadata) {
  
  alpha_estimate <- fit_object$alpha
  standard_error <- fit_object$se
  
  ci_lower <- if (is.finite(alpha_estimate) && is.finite(standard_error)) {
    alpha_estimate - qnorm(0.975) * standard_error
  } else {
    NA_real_
  }
  ci_upper <- if (is.finite(alpha_estimate) && is.finite(standard_error)) {
    alpha_estimate + qnorm(0.975) * standard_error
  } else {
    NA_real_
  }
  
  covered <- if (all(is.finite(c(ci_lower, ci_upper, true_alpha)))) {
    as.integer(true_alpha >= ci_lower && true_alpha <= ci_upper)
  } else {
    NA_integer_
  }
  
  estimated_mean_annual_af <- compute_mean_annual_af(
    burden_data = burden_data,
    alpha = alpha_estimate
  )
  
  data.table(
    scenario_id = scenario_row$scenario_id,
    scenario_label = scenario_row$scenario_label,
    outcome_nuisance_spec = scenario_row$outcome_nuisance_spec,
    exposure_nuisance_spec = scenario_row$exposure_nuisance_spec,
    replicate = as.integer(replicate_id),
    estimator = fit_object$estimator,
    true_alpha = true_alpha,
    true_rr = exp(true_alpha),
    estimate_alpha = alpha_estimate,
    estimate_rr = if (is.finite(alpha_estimate)) exp(alpha_estimate) else NA_real_,
    standard_error = standard_error,
    ci_lower_alpha = ci_lower,
    ci_upper_alpha = ci_upper,
    covered_95 = covered,
    converged = isTRUE(fit_object$converged),
    iterations = if (!is.null(fit_object$iterations)) {
      fit_object$iterations
    } else {
      NA_integer_
    },
    final_score = if (!is.null(fit_object$score)) {
      fit_object$score
    } else {
      NA_real_
    },
    true_mean_annual_af = true_mean_annual_af,
    estimated_mean_annual_af = estimated_mean_annual_af,
    mean_annual_af_error = estimated_mean_annual_af - true_mean_annual_af,
    sampled_day_event_prevalence = generation_metadata$sampled_day_event_prevalence,
    case_day_event_prevalence = generation_metadata$case_day_event_prevalence,
    proportion_sets_with_event_variation =
      generation_metadata$proportion_sets_with_event_variation,
    error_message = if (!is.null(fit_object$error_message)) {
      fit_object$error_message
    } else {
      ""
    }
  )
}

make_failed_fit <- function(estimator_name, error_message) {
  list(
    estimator = estimator_name,
    alpha = NA_real_,
    se = NA_real_,
    converged = FALSE,
    iterations = NA_integer_,
    score = NA_real_,
    error_message = error_message
  )
}

analyze_one_simulated_dataset <- function(
    simulated_object,
    scenario_row,
    analysis_cfg,
    replicate_seed) {
  
  day_data <- copy(simulated_object$day_data)
  burden_data <- copy(simulated_object$burden_data)
  generation_metadata <- copy(simulated_object$metadata)
  
  replicate_id <- unique(day_data$replicate)
  true_alpha <- unique(day_data$true_alpha_event)
  if (length(replicate_id) != 1L || length(true_alpha) != 1L) {
    stop("Replicate or true-alpha identifiers were not unique.", call. = FALSE)
  }
  
  true_mean_annual_af <- compute_mean_annual_af(
    burden_data = burden_data,
    alpha = true_alpha
  )
  
  conventional_fit <- fit_full_conventional_clogit(
    day_data = day_data,
    specification = scenario_row$outcome_nuisance_spec
  )
  
  outcome_fit <- fit_crossfitted_outcome_nuisance(
    day_data = day_data,
    specification = scenario_row$outcome_nuisance_spec
  )
  
  if (isTRUE(outcome_fit$success)) {
    day_data_for_pairs <- outcome_fit$day_data
    fold_alpha_start <- mean_or_na(outcome_fit$fold_records$alpha_event)
  } else {
    day_data_for_pairs <- add_outcome_basis(day_data)
    day_data_for_pairs[, g_hat_day := 0]
    fold_alpha_start <- NA_real_
  }
  
  pairs <- build_ordered_pseudo_pairs(day_data_for_pairs)
  
  exposure_fit <- fit_crossfitted_exposure_nuisance(
    pairs = pairs,
    specification = scenario_row$exposure_nuisance_spec,
    seed_base = replicate_seed,
    analysis_cfg = analysis_cfg
  )
  
  if (isTRUE(exposure_fit$success)) {
    pairs <- exposure_fit$pairs
  } else {
    pairs[, f_hat := 0]
  }
  
  starting_values <- list(
    conventional_fit$alpha,
    fold_alpha_start,
    0,
    log(1.05),
    log(1.15)
  )
  
  if (isTRUE(outcome_fit$success)) {
    outcome_ee <- fit_one_ee_estimator(
      estimator_name = "Outcome-model EE",
      pairs = pairs,
      g_values = pairs$g_hat_pair,
      f_values = rep(0, nrow(pairs)),
      starting_values = starting_values,
      analysis_cfg = analysis_cfg
    )
  } else {
    outcome_ee <- make_failed_fit(
      "Outcome-model EE",
      outcome_fit$error_message
    )
  }
  
  if (isTRUE(exposure_fit$success)) {
    exposure_ee <- fit_one_ee_estimator(
      estimator_name = "Exposure-regression EE",
      pairs = pairs,
      g_values = rep(0, nrow(pairs)),
      f_values = pairs$f_hat,
      starting_values = starting_values,
      analysis_cfg = analysis_cfg
    )
  } else {
    exposure_ee <- make_failed_fit(
      "Exposure-regression EE",
      exposure_fit$error_message
    )
  }
  
  if (isTRUE(outcome_fit$success) && isTRUE(exposure_fit$success)) {
    proposed_aipw <- fit_one_ee_estimator(
      estimator_name = "Proposed generalized AIPW",
      pairs = pairs,
      g_values = pairs$g_hat_pair,
      f_values = pairs$f_hat,
      starting_values = starting_values,
      analysis_cfg = analysis_cfg
    )
  } else {
    proposed_aipw <- make_failed_fit(
      "Proposed generalized AIPW",
      paste(
        c(
          if (!isTRUE(outcome_fit$success)) outcome_fit$error_message else NULL,
          if (!isTRUE(exposure_fit$success)) exposure_fit$error_message else NULL
        ),
        collapse = " | "
      )
    )
  }
  
  estimator_fits <- list(
    conventional_fit,
    outcome_ee,
    exposure_ee,
    proposed_aipw
  )
  
  result_rows <- rbindlist(lapply(estimator_fits, function(fit_object) {
    make_estimator_result_row(
      fit_object = fit_object,
      scenario_row = scenario_row,
      replicate_id = replicate_id,
      true_alpha = true_alpha,
      true_mean_annual_af = true_mean_annual_af,
      burden_data = burden_data,
      generation_metadata = generation_metadata
    )
  }), use.names = TRUE, fill = TRUE)
  
  analysis_metadata <- data.table(
    scenario_id = scenario_row$scenario_id,
    replicate = as.integer(replicate_id),
    outcome_nuisance_success = isTRUE(outcome_fit$success),
    exposure_nuisance_success = isTRUE(exposure_fit$success),
    n_ordered_pairs = nrow(pairs),
    n_informative_ordered_pairs = sum(pairs$z_event != 0),
    proportion_informative_ordered_pairs = mean(pairs$z_event != 0),
    outcome_error = outcome_fit$error_message,
    exposure_error = exposure_fit$error_message
  )
  
  list(
    result_rows = result_rows,
    analysis_metadata = analysis_metadata,
    outcome_fold_records = if (isTRUE(outcome_fit$success)) {
      outcome_fit$fold_records
    } else {
      data.table()
    },
    exposure_fold_records = if (isTRUE(exposure_fit$success)) {
      exposure_fit$fold_records
    } else {
      data.table()
    }
  )
}

# ----------------------------------------------------------------------------
# 9. Analyze and save one replicate safely
# ----------------------------------------------------------------------------

analyze_and_save_one <- function(manifest_row, scenario_row, analysis_cfg) {
  scenario_result_dir <- file.path(
    REPLICATE_RESULT_DIR,
    scenario_row$scenario_id
  )
  if (!dir.exists(scenario_result_dir)) {
    dir.create(scenario_result_dir, recursive = TRUE, showWarnings = FALSE)
  }
  
  replicate_id <- as.integer(manifest_row$replicate)
  output_path <- file.path(
    scenario_result_dir,
    sprintf("replicate_%04d_analysis.rds", replicate_id)
  )
  
  if (file.exists(output_path) && !isTRUE(analysis_cfg$overwrite)) {
    existing <- tryCatch(readRDS(output_path), error = function(e) NULL)
    if (!is.null(existing) && !is.null(existing$result_rows)) {
      return(existing)
    }
  }
  
  simulated_object <- tryCatch(
    readRDS(manifest_row$file_path),
    error = function(e) {
      structure(
        list(error_message = conditionMessage(e)),
        class = "failed_simulation_read"
      )
    }
  )
  
  if (inherits(simulated_object, "failed_simulation_read")) {
    failure_rows <- rbindlist(lapply(
      c(
        "Conventional conditional logistic regression",
        "Outcome-model EE",
        "Exposure-regression EE",
        "Proposed generalized AIPW"
      ),
      function(estimator_name) {
        data.table(
          scenario_id = scenario_row$scenario_id,
          scenario_label = scenario_row$scenario_label,
          outcome_nuisance_spec = scenario_row$outcome_nuisance_spec,
          exposure_nuisance_spec = scenario_row$exposure_nuisance_spec,
          replicate = replicate_id,
          estimator = estimator_name,
          true_alpha = NA_real_,
          true_rr = NA_real_,
          estimate_alpha = NA_real_,
          estimate_rr = NA_real_,
          standard_error = NA_real_,
          ci_lower_alpha = NA_real_,
          ci_upper_alpha = NA_real_,
          covered_95 = NA_integer_,
          converged = FALSE,
          iterations = NA_integer_,
          final_score = NA_real_,
          true_mean_annual_af = NA_real_,
          estimated_mean_annual_af = NA_real_,
          mean_annual_af_error = NA_real_,
          sampled_day_event_prevalence = NA_real_,
          case_day_event_prevalence = NA_real_,
          proportion_sets_with_event_variation = NA_real_,
          error_message = simulated_object$error_message
        )
      }
    ), fill = TRUE)
    
    analyzed <- list(
      result_rows = failure_rows,
      analysis_metadata = data.table(
        scenario_id = scenario_row$scenario_id,
        replicate = replicate_id,
        outcome_nuisance_success = FALSE,
        exposure_nuisance_success = FALSE,
        n_ordered_pairs = NA_integer_,
        n_informative_ordered_pairs = NA_integer_,
        proportion_informative_ordered_pairs = NA_real_,
        outcome_error = simulated_object$error_message,
        exposure_error = simulated_object$error_message
      ),
      outcome_fold_records = data.table(),
      exposure_fold_records = data.table()
    )
  } else {
    analyzed <- tryCatch(
      analyze_one_simulated_dataset(
        simulated_object = simulated_object,
        scenario_row = scenario_row,
        analysis_cfg = analysis_cfg,
        replicate_seed = as.integer(
          analysis_cfg$analysis_seed +
            100000L * match(
              scenario_row$scenario_id,
              analysis_cfg$all_scenarios
            ) +
            replicate_id
        )
      ),
      error = function(e) {
        error_message <- conditionMessage(e)
        failure_rows <- rbindlist(lapply(
          c(
            "Conventional conditional logistic regression",
            "Outcome-model EE",
            "Exposure-regression EE",
            "Proposed generalized AIPW"
          ),
          function(estimator_name) {
            data.table(
              scenario_id = scenario_row$scenario_id,
              scenario_label = scenario_row$scenario_label,
              outcome_nuisance_spec = scenario_row$outcome_nuisance_spec,
              exposure_nuisance_spec = scenario_row$exposure_nuisance_spec,
              replicate = replicate_id,
              estimator = estimator_name,
              true_alpha = NA_real_,
              true_rr = NA_real_,
              estimate_alpha = NA_real_,
              estimate_rr = NA_real_,
              standard_error = NA_real_,
              ci_lower_alpha = NA_real_,
              ci_upper_alpha = NA_real_,
              covered_95 = NA_integer_,
              converged = FALSE,
              iterations = NA_integer_,
              final_score = NA_real_,
              true_mean_annual_af = NA_real_,
              estimated_mean_annual_af = NA_real_,
              mean_annual_af_error = NA_real_,
              sampled_day_event_prevalence = NA_real_,
              case_day_event_prevalence = NA_real_,
              proportion_sets_with_event_variation = NA_real_,
              error_message = error_message
            )
          }
        ), fill = TRUE)
        
        list(
          result_rows = failure_rows,
          analysis_metadata = data.table(
            scenario_id = scenario_row$scenario_id,
            replicate = replicate_id,
            outcome_nuisance_success = FALSE,
            exposure_nuisance_success = FALSE,
            n_ordered_pairs = NA_integer_,
            n_informative_ordered_pairs = NA_integer_,
            proportion_informative_ordered_pairs = NA_real_,
            outcome_error = error_message,
            exposure_error = error_message
          ),
          outcome_fold_records = data.table(),
          exposure_fold_records = data.table()
        )
      }
    )
  }
  
  temporary_path <- paste0(
    output_path,
    ".tmp_",
    Sys.getpid(),
    "_",
    sample.int(1000000L, 1L)
  )
  saveRDS(analyzed, temporary_path, compress = "gzip")
  if (file.exists(output_path)) unlink(output_path)
  renamed <- file.rename(temporary_path, output_path)
  if (!renamed) {
    unlink(temporary_path)
    stop("Failed to save analysis result: ", output_path, call. = FALSE)
  }
  
  analyzed
}

# ----------------------------------------------------------------------------
# 10. Main analysis loop
# ----------------------------------------------------------------------------

message("Extreme-event simulation analysis")
message("Input directory: ", INPUT_DIR)
message("Result directory: ", RESULT_DIR)
message("Replicate files selected: ", nrow(manifest))
message("Parallel workers: ", analysis_cfg$n_workers)
message("XGBoost threads per model: ", analysis_cfg$xgb_threads)
message("Overwrite existing replicate analyses: ", analysis_cfg$overwrite)

scenario_analysis_objects <- vector("list", nrow(scenario_design))

for (scenario_index in seq_len(nrow(scenario_design))) {
  scenario_row <- as.list(scenario_design[scenario_index])
  scenario_manifest <- manifest[scenario_id == scenario_row$scenario_id]
  
  if (nrow(scenario_manifest) == 0L) {
    warning("No replicate files found for scenario: ", scenario_row$scenario_id)
    next
  }
  
  message(
    "Analyzing scenario ",
    scenario_index,
    "/",
    nrow(scenario_design),
    ": ",
    scenario_row$scenario_id,
    " (",
    nrow(scenario_manifest),
    " replicates)"
  )
  
  manifest_rows <- split(
    scenario_manifest,
    seq_len(nrow(scenario_manifest))
  )
  
  if (.Platform$OS.type == "unix" && analysis_cfg$n_workers > 1L) {
    scenario_results <- parallel::mclapply(
      manifest_rows,
      FUN = function(manifest_row_dt) {
        analyze_and_save_one(
          manifest_row = as.list(manifest_row_dt[1L]),
          scenario_row = scenario_row,
          analysis_cfg = analysis_cfg
        )
      },
      mc.cores = analysis_cfg$n_workers,
      mc.preschedule = FALSE,
      mc.set.seed = FALSE
    )
  } else {
    scenario_results <- lapply(seq_along(manifest_rows), function(index) {
      result <- analyze_and_save_one(
        manifest_row = as.list(manifest_rows[[index]][1L]),
        scenario_row = scenario_row,
        analysis_cfg = analysis_cfg
      )
      
      progress_interval <- max(1L, floor(length(manifest_rows) / 10L))
      if (index %% progress_interval == 0L || index == length(manifest_rows)) {
        message(
          "  Completed replicate ",
          index,
          " of ",
          length(manifest_rows)
        )
      }
      result
    })
  }
  
  scenario_analysis_objects[[scenario_index]] <- scenario_results
}

all_analysis_objects <- unlist(
  scenario_analysis_objects,
  recursive = FALSE
)
all_analysis_objects <- all_analysis_objects[!vapply(
  all_analysis_objects,
  is.null,
  logical(1)
)]

if (length(all_analysis_objects) == 0L) {
  stop("No simulation analyses were completed.", call. = FALSE)
}

replicate_results <- rbindlist(
  lapply(all_analysis_objects, `[[`, "result_rows"),
  use.names = TRUE,
  fill = TRUE
)
analysis_metadata <- rbindlist(
  lapply(all_analysis_objects, `[[`, "analysis_metadata"),
  use.names = TRUE,
  fill = TRUE
)
outcome_fold_records <- rbindlist(
  lapply(all_analysis_objects, `[[`, "outcome_fold_records"),
  use.names = TRUE,
  fill = TRUE,
  idcol = "analysis_object_index"
)
exposure_fold_records <- rbindlist(
  lapply(all_analysis_objects, `[[`, "exposure_fold_records"),
  use.names = TRUE,
  fill = TRUE,
  idcol = "analysis_object_index"
)

# ----------------------------------------------------------------------------
# 11. Scenario-specific and overall performance summaries
# ----------------------------------------------------------------------------

estimator_order <- c(
  "Conventional conditional logistic regression",
  "Outcome-model EE",
  "Exposure-regression EE",
  "Proposed generalized AIPW"
)
scenario_order <- analysis_cfg$all_scenarios

replicate_results[, alpha_error := estimate_alpha - true_alpha]
replicate_results[, finite_estimate := is.finite(estimate_alpha)]

scenario_summary <- replicate_results[, .(
  n_replicates = .N,
  n_finite_estimates = sum(finite_estimate),
  empirical_coefficient_bias = mean_or_na(alpha_error),
  absolute_empirical_coefficient_bias = abs(mean_or_na(alpha_error)),
  mean_annual_af_empirical_bias = mean_or_na(mean_annual_af_error),
  mean_annual_af_absolute_bias = abs(mean_or_na(mean_annual_af_error)),
  empirical_coverage_95_percent = 100 * mean_or_na(covered_95),
  convergence_rate_percent = 100 * mean(converged %in% TRUE),
  nonfinite_estimate_rate_percent = 100 * mean(!finite_estimate),
  mean_estimated_standard_error = mean_or_na(standard_error),
  mean_sampled_day_event_prevalence = mean_or_na(
    sampled_day_event_prevalence
  ),
  mean_case_day_event_prevalence = mean_or_na(case_day_event_prevalence),
  mean_proportion_sets_with_event_variation = mean_or_na(
    proportion_sets_with_event_variation
  )
), by = .(
  scenario_id,
  scenario_label,
  estimator
)]

scenario_summary[, scenario_order_index := match(scenario_id, scenario_order)]
scenario_summary[, estimator_order_index := match(estimator, estimator_order)]
setorder(scenario_summary, scenario_order_index, estimator_order_index)
scenario_summary[, c("scenario_order_index", "estimator_order_index") := NULL]

primary_summary <- scenario_summary[
  scenario_id %in% analysis_cfg$primary_scenarios,
  .(
    overall_mean_absolute_coefficient_bias = mean_or_na(
      absolute_empirical_coefficient_bias
    ),
    worst_case_absolute_coefficient_bias = max_or_na(
      absolute_empirical_coefficient_bias
    ),
    overall_mean_absolute_mean_annual_af_bias = mean_or_na(
      mean_annual_af_absolute_bias
    ),
    mean_empirical_coverage_95_percent = mean_or_na(
      empirical_coverage_95_percent
    )
  ),
  by = estimator
]

minimum_convergence <- scenario_summary[, .(
  minimum_convergence_rate_percent = min_or_na(convergence_rate_percent)
), by = estimator]

primary_summary <- merge(
  primary_summary,
  minimum_convergence,
  by = "estimator",
  all = TRUE,
  sort = FALSE
)
primary_summary[, estimator_order_index := match(estimator, estimator_order)]
setorder(primary_summary, estimator_order_index)
primary_summary[, estimator_order_index := NULL]

# Generation and identification summaries.
generation_summary <- unique(replicate_results[, .(
  scenario_id,
  replicate,
  sampled_day_event_prevalence,
  case_day_event_prevalence,
  proportion_sets_with_event_variation
)])[, .(
  mean_sampled_day_event_prevalence = mean_or_na(
    sampled_day_event_prevalence
  ),
  mean_case_day_event_prevalence = mean_or_na(case_day_event_prevalence),
  mean_proportion_sets_with_event_variation = mean_or_na(
    proportion_sets_with_event_variation
  )
), by = scenario_id]

# ----------------------------------------------------------------------------
# 12. Construct the compact transposed comparison table
# ----------------------------------------------------------------------------

get_scenario_metric <- function(scenario_id_value, estimator_name) {
  scenario_summary[
    scenario_id == scenario_id_value & estimator == estimator_name,
    absolute_empirical_coefficient_bias
  ][1L]
}

get_primary_metric <- function(metric_name, estimator_name) {
  primary_summary[
    estimator == estimator_name,
    get(metric_name)
  ][1L]
}

compact_rows <- list()
row_index <- 0L

scenario_metric_labels <- c(
  "Both nuisance models correct: absolute coefficient bias ↓",
  "Outcome correct; exposure misspecified: absolute coefficient bias ↓",
  "Outcome misspecified; exposure correct: absolute coefficient bias ↓",
  "Both nuisance models misspecified: absolute coefficient bias ↓"
)

for (scenario_index in seq_along(scenario_order)) {
  row_index <- row_index + 1L
  compact_rows[[row_index]] <- data.table(
    performance_metric = scenario_metric_labels[scenario_index],
    conventional = get_scenario_metric(
      scenario_order[scenario_index],
      estimator_order[1L]
    ),
    outcome_ee = get_scenario_metric(
      scenario_order[scenario_index],
      estimator_order[2L]
    ),
    exposure_ee = get_scenario_metric(
      scenario_order[scenario_index],
      estimator_order[3L]
    ),
    proposed_aipw = get_scenario_metric(
      scenario_order[scenario_index],
      estimator_order[4L]
    )
  )
}

summary_metric_map <- list(
  list(
    label = paste0(
      "Overall mean absolute coefficient bias across the three ",
      "double-robustness scenarios ↓"
    ),
    field = "overall_mean_absolute_coefficient_bias"
  ),
  list(
    label = paste0(
      "Worst-case absolute coefficient bias across the three ",
      "double-robustness scenarios ↓"
    ),
    field = "worst_case_absolute_coefficient_bias"
  ),
  list(
    label = paste0(
      "Overall mean absolute mean annual AF bias across the three ",
      "double-robustness scenarios ↓"
    ),
    field = "overall_mean_absolute_mean_annual_af_bias"
  ),
  list(
    label = paste0(
      "Mean 95% confidence interval coverage across the three ",
      "double-robustness scenarios (%) → 95"
    ),
    field = "mean_empirical_coverage_95_percent"
  ),
  list(
    label = "Minimum convergence across all four scenarios (%) ↑",
    field = "minimum_convergence_rate_percent"
  )
)

for (metric_definition in summary_metric_map) {
  row_index <- row_index + 1L
  compact_rows[[row_index]] <- data.table(
    performance_metric = metric_definition$label,
    conventional = get_primary_metric(
      metric_definition$field,
      estimator_order[1L]
    ),
    outcome_ee = get_primary_metric(
      metric_definition$field,
      estimator_order[2L]
    ),
    exposure_ee = get_primary_metric(
      metric_definition$field,
      estimator_order[3L]
    ),
    proposed_aipw = get_primary_metric(
      metric_definition$field,
      estimator_order[4L]
    )
  )
}

compact_table <- rbindlist(compact_rows, use.names = TRUE, fill = TRUE)
setnames(
  compact_table,
  c("conventional", "outcome_ee", "exposure_ee", "proposed_aipw"),
  estimator_order
)

# ----------------------------------------------------------------------------
# 13. Save machine-readable output files
# ----------------------------------------------------------------------------

fwrite(
  replicate_results,
  file.path(RESULT_DIR, "extreme_event_simulation_replicate_results.csv")
)
fwrite(
  scenario_summary,
  file.path(RESULT_DIR, "extreme_event_simulation_scenario_summary.csv")
)
fwrite(
  primary_summary,
  file.path(RESULT_DIR, "extreme_event_simulation_primary_summary.csv")
)
fwrite(
  compact_table,
  file.path(RESULT_DIR, "extreme_event_simulation_compact_table.csv")
)
fwrite(
  analysis_metadata,
  file.path(RESULT_DIR, "extreme_event_simulation_analysis_metadata.csv")
)
fwrite(
  generation_summary,
  file.path(RESULT_DIR, "extreme_event_simulation_generation_summary.csv")
)

saveRDS(
  list(
    replicate_results = replicate_results,
    scenario_summary = scenario_summary,
    primary_summary = primary_summary,
    compact_table = compact_table,
    analysis_metadata = analysis_metadata,
    outcome_fold_records = outcome_fold_records,
    exposure_fold_records = exposure_fold_records,
    generation_summary = generation_summary,
    analysis_configuration = analysis_cfg,
    simulation_configuration = simulation_configuration,
    completed_at = Sys.time()
  ),
  file.path(RESULT_DIR, "extreme_event_simulation_complete_results.rds"),
  compress = "gzip"
)

# ----------------------------------------------------------------------------
# 14. Create formatted Excel workbook
# ----------------------------------------------------------------------------

workbook <- openxlsx::createWorkbook()
openxlsx::addWorksheet(workbook, "Estimator_Comparison")
openxlsx::addWorksheet(workbook, "Scenario_Long")
openxlsx::addWorksheet(workbook, "Primary_Summary")
openxlsx::addWorksheet(workbook, "Replicate_Results")
openxlsx::addWorksheet(workbook, "Generation_Diagnostics")

# Styles
# Styles
style_title <- openxlsx::createStyle(
  fontSize = 14,
  fontColour = "#FFFFFF",
  fgFill = "#1F4E78",
  textDecoration = "bold",
  halign = "center",
  valign = "center"
)

style_subtitle <- openxlsx::createStyle(
  fontSize = 9,
  fontColour = "#404040",
  textDecoration = "italic",
  halign = "center",
  valign = "center",
  wrapText = TRUE
)

style_header <- openxlsx::createStyle(
  fontColour = "#FFFFFF",
  fgFill = "#5B9BD5",
  textDecoration = "bold",
  halign = "center",
  valign = "center",
  wrapText = TRUE,
  border = "TopBottomLeftRight",
  borderColour = "#D9E2F3"
)

style_body <- openxlsx::createStyle(
  halign = "center",
  valign = "center",
  wrapText = TRUE,
  border = "TopBottomLeftRight",
  borderColour = "#D9D9D9"
)

style_metric <- openxlsx::createStyle(
  halign = "left",
  valign = "center",
  wrapText = TRUE,
  border = "TopBottomLeftRight",
  borderColour = "#D9D9D9"
)

style_aipw <- openxlsx::createStyle(
  fgFill = "#E2F0D9",
  textDecoration = "bold",
  halign = "center",
  valign = "center",
  border = "TopBottomLeftRight",
  borderColour = "#70AD47"
)

style_summary_metric <- openxlsx::createStyle(
  fgFill = "#D9EAF7",
  textDecoration = "bold",
  halign = "left",
  valign = "center",
  wrapText = TRUE,
  border = "TopBottomLeftRight",
  borderColour = "#A6A6A6"
)

style_number4 <- openxlsx::createStyle(numFmt = "0.0000")
style_number1 <- openxlsx::createStyle(numFmt = "0.00")

comparison_sheet <- "Estimator_Comparison"
openxlsx::mergeCells(workbook, comparison_sheet, cols = 1:5, rows = 1)
openxlsx::writeData(
  workbook,
  comparison_sheet,
  "Simulation performance across four nuisance-model specification scenarios",
  startCol = 1,
  startRow = 1,
  colNames = FALSE
)
openxlsx::addStyle(
  workbook,
  comparison_sheet,
  style_title,
  rows = 1,
  cols = 1:5,
  gridExpand = TRUE
)
openxlsx::setRowHeights(workbook, comparison_sheet, rows = 1, heights = 30)

actual_replicates <- scenario_summary[, unique(n_replicates)]
replicate_text <- if (length(actual_replicates) == 1L) {
  paste0(
    "Based on ",
    actual_replicates,
    " Monte Carlo replicates per scenario. Scenario-specific results are ",
    "shown for all four scenarios; overall summaries use the three scenarios ",
    "in which at least one nuisance model was correctly specified."
  )
} else {
  paste0(
    "The number of Monte Carlo replicates varied across scenarios. ",
    "Scenario-specific results are shown for all four scenarios; overall ",
    "summaries use the three scenarios in which at least one nuisance model ",
    "was correctly specified."
  )
}

openxlsx::mergeCells(workbook, comparison_sheet, cols = 1:5, rows = 2)
openxlsx::writeData(
  workbook,
  comparison_sheet,
  replicate_text,
  startCol = 1,
  startRow = 2,
  colNames = FALSE
)
openxlsx::addStyle(
  workbook,
  comparison_sheet,
  style_subtitle,
  rows = 2,
  cols = 1:5,
  gridExpand = TRUE
)
openxlsx::setRowHeights(workbook, comparison_sheet, rows = 2, heights = 32)

openxlsx::writeData(
  workbook,
  comparison_sheet,
  compact_table,
  startCol = 1,
  startRow = 4,
  colNames = TRUE,
  rowNames = FALSE
)

n_compact_rows <- nrow(compact_table)
openxlsx::addStyle(
  workbook,
  comparison_sheet,
  style_header,
  rows = 4,
  cols = 1:5,
  gridExpand = TRUE
)
openxlsx::addStyle(
  workbook,
  comparison_sheet,
  style_body,
  rows = 5:(4 + n_compact_rows),
  cols = 2:5,
  gridExpand = TRUE
)
openxlsx::addStyle(
  workbook,
  comparison_sheet,
  style_metric,
  rows = 5:(4 + n_compact_rows),
  cols = 1,
  gridExpand = TRUE
)
openxlsx::addStyle(
  workbook,
  comparison_sheet,
  style_aipw,
  rows = 5:(4 + n_compact_rows),
  cols = 5,
  gridExpand = TRUE,
  stack = TRUE
)
openxlsx::addStyle(
  workbook,
  comparison_sheet,
  style_summary_metric,
  rows = 9:(4 + n_compact_rows),
  cols = 1,
  gridExpand = TRUE,
  stack = TRUE
)

# Bias rows use four decimals; coverage and convergence rows use one decimal.
openxlsx::addStyle(
  workbook,
  comparison_sheet,
  style_number4,
  rows = 5:11,
  cols = 2:5,
  gridExpand = TRUE,
  stack = TRUE
)
openxlsx::addStyle(
  workbook,
  comparison_sheet,
  style_number1,
  rows = 12:13,
  cols = 2:5,
  gridExpand = TRUE,
  stack = TRUE
)

openxlsx::setColWidths(
  workbook,
  comparison_sheet,
  cols = 1,
  widths = 52
)
openxlsx::setColWidths(
  workbook,
  comparison_sheet,
  cols = 2:5,
  widths = 22
)
openxlsx::setRowHeights(
  workbook,
  comparison_sheet,
  rows = 4,
  heights = 52
)
openxlsx::setRowHeights(
  workbook,
  comparison_sheet,
  rows = 5:(4 + n_compact_rows),
  heights = 32
)
openxlsx::freezePane(
  workbook,
  comparison_sheet,
  firstActiveRow = 5,
  firstActiveCol = 2
)

note_start_row <- 4 + n_compact_rows + 2
notes <- c(
  "Notes:",
  paste0(
    "The first four rows report scenario-specific absolute empirical bias for ",
    "the additional event-history log mortality rate-ratio coefficient."
  ),
  paste0(
    "Overall coefficient-bias, worst-case-bias, attributable-fraction-bias, ",
    "and coverage summaries are calculated across the three scenarios in ",
    "which at least one nuisance model was correctly specified."
  ),
  paste0(
    "The both-misspecified scenario is shown to evaluate the boundary of the ",
    "double-robustness property but is not pooled into the primary overall ",
    "summaries."
  ),
  paste0(
    "Arrows indicate the preferred direction: lower bias is better, higher ",
    "convergence is better, and coverage is best when close to 95%."
  ),
  "AF, attributable fraction; AIPW, augmented inverse probability weighting; EE, estimating equation."
)

for (note_index in seq_along(notes)) {
  row_value <- note_start_row + note_index - 1L
  openxlsx::mergeCells(
    workbook,
    comparison_sheet,
    cols = 1:5,
    rows = row_value
  )
  openxlsx::writeData(
    workbook,
    comparison_sheet,
    notes[note_index],
    startCol = 1,
    startRow = row_value,
    colNames = FALSE
  )
}

# Additional data sheets.
openxlsx::writeDataTable(
  workbook,
  "Scenario_Long",
  scenario_summary,
  tableStyle = "TableStyleMedium2"
)
openxlsx::writeDataTable(
  workbook,
  "Primary_Summary",
  primary_summary,
  tableStyle = "TableStyleMedium2"
)
openxlsx::writeDataTable(
  workbook,
  "Replicate_Results",
  replicate_results,
  tableStyle = "TableStyleMedium2"
)
openxlsx::writeDataTable(
  workbook,
  "Generation_Diagnostics",
  generation_summary,
  tableStyle = "TableStyleMedium2"
)

for (sheet_name in c(
  "Scenario_Long",
  "Primary_Summary",
  "Replicate_Results",
  "Generation_Diagnostics"
)) {
  openxlsx::freezePane(workbook, sheet_name, firstActiveRow = 2)
  openxlsx::setColWidths(workbook, sheet_name, cols = 1:50, widths = "auto")
}

excel_path <- file.path(
  RESULT_DIR,
  "extreme_event_aipw_simulation_estimator_comparison.xlsx"
)
openxlsx::saveWorkbook(workbook, excel_path, overwrite = TRUE)

writeLines(
  c(
    "Extreme-temperature event-history generalized-AIPW simulation analysis",
    "",
    paste0("Replicate files analyzed: ", nrow(manifest)),
    paste0("Parallel workers: ", analysis_cfg$n_workers),
    paste0("XGBoost threads per model: ", analysis_cfg$xgb_threads),
    "",
    paste0("Main Excel output: ", excel_path)
  ),
  con = file.path(RESULT_DIR, "README_analysis.txt")
)

message("Extreme-event simulation analysis completed successfully.")
message("Main Excel output: ", excel_path)
message(
  "Replicate-level results: ",
  file.path(RESULT_DIR, "extreme_event_simulation_replicate_results.csv")
)